## NUMPY

In [2]:
import numpy as np

a = [1,2,4,8,5]

print(np.__version__)
print(np.sum(a))
print(np.mean(a))
print(np.average(a))
print(np.median(a))

2.1.1
20
4.0
4.0
4.0


In [3]:
X = np.array([[1,2,4,8,5], [1,2,4,8,5], [1,2,4,8,5]])
print(X)

[[1 2 4 8 5]
 [1 2 4 8 5]
 [1 2 4 8 5]]


In [4]:
X.dtype

dtype('int64')

In [5]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x=np.arange(10).reshape((2,5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
num = [1,2,4,8,5]
type(num)

list

In [8]:
np_from_list = np.array(num)
display(type(np_from_list))
np_from_list

numpy.ndarray

array([1, 2, 4, 8, 5])

In [9]:
np_from_list.dtype

dtype('int64')

In [10]:
np_from_list = np.array(num, dtype = np.float64)
display(type(np_from_list))
np_from_list

numpy.ndarray

array([1., 2., 4., 8., 5.])

In [11]:
np_from_list.dtype

dtype('float64')

In [12]:
lst_2d = [[1,2,3],[1,2,3],[1,2,3]]
lst_2d

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [13]:
type(lst_2d)

list

In [14]:
np_from_2d_list = np.array(lst_2d)
display(type(np_from_2d_list))
np_from_2d_list

numpy.ndarray

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [15]:
np_from_2d_list = np.array(lst_2d, dtype = np.float16)
display(type(np_from_2d_list))
np_from_2d_list

numpy.ndarray

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]], dtype=float16)

In [16]:
x1 = np.array([[[1,2,3,4,5], [4,5,6,7,8]],
               [[7,8,9,4,5],
                [3,6,9,8,5]]])
print(type(x1))
x1

<class 'numpy.ndarray'>


array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]],

       [[7, 8, 9, 4, 5],
        [3, 6, 9, 8, 5]]])

In [17]:
x1.shape

(2, 2, 5)

In [18]:
x1.ndim

3

In [19]:
x2 = np.array([[[0,1,2,3,4],[5,6,7,8,9]],[list('abcde'),list('fghij')]])
x2

array([[['0', '1', '2', '3', '4'],
        ['5', '6', '7', '8', '9']],

       [['a', 'b', 'c', 'd', 'e'],
        ['f', 'g', 'h', 'i', 'j']]], dtype='<U21')

In [20]:
x2[0]

array([['0', '1', '2', '3', '4'],
       ['5', '6', '7', '8', '9']], dtype='<U21')

In [21]:
x2[:,1]

array([['5', '6', '7', '8', '9'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U21')

In [22]:
x2[:,:,1]

array([['1', '6'],
       ['b', 'g']], dtype='<U21')

In [23]:
print(x.dtype.name)

int64


In [24]:
y = np.ndarray((2,3,4),dtype=np.float128)

In [25]:
for dtp in [np.float16,np.float32,np.float64]:
    print(f'''for {dtp}):
          -min value: {np.finfo(dtp).min}
          -max value: {np.finfo(dtp).max}
          -epsilon value: {np.finfo(dtp).eps}
    ''')

for <class 'numpy.float16'>):
          -min value: -65504.0
          -max value: 65504.0
          -epsilon value: 0.0009765625
    
for <class 'numpy.float32'>):
          -min value: -3.4028234663852886e+38
          -max value: 3.4028234663852886e+38
          -epsilon value: 1.1920928955078125e-07
    
for <class 'numpy.float64'>):
          -min value: -1.7976931348623157e+308
          -max value: 1.7976931348623157e+308
          -epsilon value: 2.220446049250313e-16
    


In [26]:
ary_zeros = np.zeros((3,3),dtype=np.int16,order='C')
ary_zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [29]:
ary_ones = np.ones((3, 3),dtype=np.int16,order='C')
ary_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)